import "inspectable.idl";
import "Windows.Foundation.idl";

namespace MyNamespace
{
    [uuid(61DEBD51-F187-41CD-B2DE-5B7F1822F0BA)] // Random GUID
    [version(0x00000001)]
    interface IMyInterface : IInspectable
    {
      HRESULT GetUsername([out] [retval] HSTRING* username);
    }
}
